### PR TITLE
Update RPG-Items for 1.6.2

### PR DESCRIPTION
**Pull request by TfT-02**
Hi, I just quickly updated RPG-Items to 1.6 whilst keeping compatibility with 1.5.

### CODE REVIEW

**Comment by Thinkofname** [comment]
I'm not updating this anymore but I have no issues with you taking over the project on bukkitdev to update it if you want

**Comment by TfT-02** [comment]
I see. I'd like to take this over. Though it won't be until this weekend that I have enough time to dive into active development.

If you can add me on BukkitDev, I will upload a quick patch version for 1.6 and more updates later on.

**Comment by Thinkofname** [comment]
Done

**Comment by TfT-02** [comment]
Oh and, would you like me to use a fork of your Github repo for further development or would you prefer if I use yours, adding me as a collaborator?

_Edit:_ I guess it makes more sense to use my forked repo.

**Comment by Thinkofname** [comment]
Just a note: The version should be 3.4 otherwise the autoupdater breaks

**Comment by TfT-02** [comment]
Oh :/ Good to let me know, I'll have to re-upload the file then.

I can't seem to mark the project as not-abandonent? Is that intentional or do I not have the right permissions?

**Comment by Thinkofname** [comment]
Erm.. not sure let me look

**Comment by Thinkofname** [comment]
Try now

**Comment by Thinkofname** [comment]
I changed the name of the upload but I think the version will need changing in the plugin.yml as well

**Comment by TfT-02** [comment]
Alright, will do that now. Thanks a lot! Everything is working now.

**Comment by Thinkofname** [comment]
np

**Pull request closed without merging**
